export const strings = {
  logo: 'Control citas',
  home: 'Inicio',
  services: 'Servicios',
  followus: 'Siguenos en',
  contact: 'Contacto',
  about: 'Acerca de',
  register_of_employees: 'Registro de empleados',
  register_of_sucursal: 'Registro de sucursales',
  register_employee: 'Registrar empleado',
  register_employees: 'Registrar empleados',
  register_services: 'Registrar servicios',
  register_sucursales: 'Registrar sucursales',
  edit_sucursal: 'Editar Sucursales',
  alert1: 'Algunos de los campos no han sido llenados o estan incorrectos revisalos otra vez',
  alert2: 'Las contraseñas no coinciden, intenta otra vez',
  alert3: 'Algo salió mal, revisa que tu correo no este ya registrado',
  alert4: 'Empleado registrado correctamente',
  alert5: 'Correo o contraseña incorrectos',
  alert6: 'Registro Exitoso!',
  alert7: 'Agregar 10 digitos',
  alert8: 'Agregar 5 digitos',
  password: 'Contraseña',
  email_address: 'Dirección email',
  company: 'Empresa',
  administrator: 'Administrador',
  employee: 'Empleado',
  role: 'Rol',
  phone: 'Teléfono',
  surname1: 'Apellido paterno',
  surname2: 'Apellido materno',
  name: 'Nombre',
  login: 'Inicia sesión',
  look: 'Buscar',
  cp: 'C.P.',
  suburb: 'Colonia',
  street: 'Calle',
  outdoor_number: 'Número Exterior',
  interior_number: 'Número Interior',
  latitude:'Latitud',
  length:'Longitud' 
};
