export const strings = {
  logo: 'Control citas',
  home: 'Inicio',
  services: 'Servicios',
  followus: 'Siguenos en',
  contact: 'Contacto',
  about: 'Acerca de',
  register_of_employees: 'Registro de empleados',
  register_employee: 'Registrar empleado',
  register_employees: 'Registrar empleados',
  register_services: 'Registrar servicios',
  alert1: 'Algunos de los campos no han sido llenados o estan incorrectos revisalos otra vez',
  alert2: 'Las contraseñas no coinciden, intenta otra vez',
  alert3: 'Algo salió mal, revisa que tu correo no este ya registrado',
  alert4: 'Empleado registrado correctamente',
  alert5: 'Correo o contraseña incorrectos',
  alert6: 'El registro se hizo correctamente',
  alert7: 'El registro se actualizó correctamente',
  alert8: 'El campo no ha sido llenado!!',
  alert9: 'No se encontraron servicios inactivos',
  password: 'Contraseña',
  email_address: 'Dirección email',
  email: 'Email',
  company: 'Empresa',
  administrator: 'Administrador',
  employee: 'Empleado',
  role: 'Rol',
  phone: 'Teléfono',
  surname1: 'Apellido paterno',
  surname2: 'Apellido materno',
  name: 'Nombre',
  login: 'Inicia sesión',
  look: 'Buscar',
  description: 'Descripción',
  cost: 'Costo',
  cost_of_the_service: 'Costo del servicio',
  image: 'Image',
  add: 'Agregar',
  reactivate_services: 'Reactivar servicios',
  show_all: 'Mostrar todos',
  look_by_name: 'Buscar por nombre',
  edit: 'Editar',
  deactivate: 'Desactivar',
  return: 'Regresar',
  reactivate: 'Reactivar',
  repeat_your_password: 'repite tu contraseña',
  min_password: 'Minimo 6 caracteres',
  length_password: '10 dígitos',
  email_example: 'Ejem. juan@gmail.com',
  surname_example1: 'Ejem. López',
  surname_example2: 'Ejem. Muñoz',
  name_example: 'Ejem. Juan',
};
